version: "3"
services:
  registry:
    image: 'node-docker:latest'
    hostname: registry
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
  service1:
    image: 'node-docker:latest'
    hostname: service1
    links:
      - registry
    depends_on:
      - registry
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
      - REGISTRY_HOST=registry
